app/members/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser, UserManager as DjangoManager

from movies.models import Movie


class UserManager(DjangoManager): # 이렇게 오버라이드 해주면 UserManager동작을 우리가 언제든지 바꿀 수 있다.
    pass


class User(AbstractUser):
    img_profile = models.ImageField(upload_to="user", blank=True)
    password2 = models.CharField(max_length=255,blank=True)
    phone_number = models.CharField(max_length=255,blank=True)
    movie = models.ManyToManyField(Movie,through='MovieLike',blank=True)
    objects = UserManager()
    set_alarm_before_24h = models.BooleanField(default=False)
    set_alarm_before_3h = models.BooleanField(default=False)
    set_alarm_before_half_h = models.BooleanField(default=False)

    @property
    def like_movies(self):
        like_movie_list = list()

        for movielike in self.movielike_set.all():
            like_movie_list.append(movielike.movie)

        return like_movie_list


class MovieLike(models.Model):
    movie = models.ForeignKey(
        Movie,
        on_delete=models.CASCADE
   )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)

app/members/apis/__init__.py
from .signup import *
from .user_detail import *
from .login import *
from .logout import *
from .signout import *

app/members/serializers/__init__.py
from .user import *
from .user_detail import *

app/members/urls/views.py
from django.urls import path, include
from ..import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'members'

urlpatterns = [

    path('login_page/', views.login_page, name='login_page'),
    path('normal_login/', views.normal_login, name='normal_login'),
    path('logout_view/',views.logout_view, name='logout_view'),
    path('signup_page/', views.signup,name='signup_page'),
    path('activate/<str:uidb64>/<str:token>', views.user_activate, name='activate'),
    path('signout_view/',views.signout_view, name='signout_view'),

    path('facebook_login/', views.facebook_login, name='facebook_login'),
    path('kakaotalk_login/', views.kakaotalk_login, name='kakaotalk_login'),
    path('naver_login/', views.naver_login, name='naver_login'),
    path('google_login/', views.google_login, name='google_login'),

    path('user_detail_page/', views.user_detail_page, name='user_detail_page'),

    path('user_info_change/', views.user_info_change_page, name='user_info_change_page'),
    path('user_password_change_page/', views.user_password_change_page, name='user_password_change_page'),
    path('user_password_change/<str:uidb64>/<str:token>/<str:password>', views.user_password_change, name='user_password_change'),
    path('user_email_change_page/', views.user_email_change_page, name='user_email_change_page'),
    path('user_email_change/<str:uidb64>/<str:token>/<str:email>', views.user_email_change,name='user_email_change'),
    path('user_phone_number_change_page/', views.user_phone_number_change_page, name='user_phone_number_change_page'),
    path('user_phone_number_change/<str:uidb64>/<str:token>/<str:phone_number>', views.user_phone_number_change, name='user_phone_number_change'),

    path('user_detail_page/user_movie_like_page/', views.user_movie_like_page, name='user_movie_like_page'),
    path('user_detail_page/<int:pk>/user_movie_like/', views.user_movie_like, name = 'user_movie_like'),

    path('user_detail_page/user_set_alarm_page/', views.user_set_alarm_page, name = 'user_set_alarm_page'),
    path('user_detail_page/<int:type_num>/user_set_alarm/', views.user_set_alarm, name = 'user_set_alarm'),

]+ static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

app/members/views.py
import inspect
import sys

import django
from django.contrib.auth import get_user_model, login
from django.http import HttpResponse
from django.shortcuts import render, redirect
import requests

# Create your views here.
import members
from config.settings.base import *
User = get_user_model()


def normal_login(request):


    if request.method == 'POST':
        return render(request, 'normal_login_succed.html')

    else:
        return render(request,'members/login.html')


def facebook_login(request):

    # access token 얻기

    code = request.GET.get('code')
    url = 'https://graph.facebook.com/v3.0/oauth/access_token'

    redirect_uri = 'https://maro5.com/members/facebook_login/'
    RUNSERVER = 'runserver' in sys.argv
    if RUNSERVER:
        redirect_uri = 'http://localhost:8000/members/facebook_login/'

    params = {
        'client_id':FACEBOOK_APP_ID,
        'redirect_uri':redirect_uri ,
        'client_secret':FACEBOOK_APP_SECRET_CODE,
        'code':code,
    }

    response = requests.get(url,params)
    response_dict = response.json()
    access_token = response_dict['access_token']






    # aceess token 검사 --> fb id등 정보 받기

    url = 'https://graph.facebook.com/debug_token'

    params = {
        'input_token':access_token,
        'access_token':'{}|{}'.format(
            FACEBOOK_APP_ID, FACEBOOK_APP_SECRET_CODE
        )
    }
    response = requests.get(url, params)

    # 위에서 받은 response중 이름등 추가적 가져오기 위해서 scope를 전달해 줘야 한다. ----> http에 추가해 놓았다.






    # GraphAPI를 통햬써 Facebook User정보 받아오기.
    url = 'https://graph.facebook.com/v3.0/me'

    params = {
        'fields':
            ','.join(['id', 'name', 'first_name', 'last_name', 'picture']),
        'access_token': access_token,
    }
    response = requests.get(url, params)
    response_dict = response.json()




    # 받아온 정보 중 회원가입에 필요한 요소들 꺼내기
    facebook_user_id = response_dict['id']
    first_name = response_dict['first_name']
    last_name = response_dict['last_name']
    url_img_profile = response_dict['picture']['data']['url']

    # 있으면 get없으면 create하고 True도 같이 반환 .
    user, user_created = User.objects.get_or_create(
        username = facebook_user_id,
        defaults = {
            'first_name': first_name,
            'last_name': last_name,
        }
    )

    login(request, user,backend='django.contrib.auth.backends.ModelBackend')

    # return redirect('index')

    if user is not None:
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')

        # 어떤 함수 테스트 중인지도 전달해 주겠다.
        frame = inspect.currentframe()
        function_name = inspect.getframeinfo(frame).function
        context = {'function_name': function_name}

        return render(request,'social_login_succed.html',context)

    return redirect('login_page')

def kakaotalk_login(request):

    # 1. code 받기
    code = request.GET.get('code')
    # return HttpResponse(code)


    # 2 .access token 받기
    url = "https://kauth.kakao.com/oauth/token"
    kakaotalk_redirect_uri = 'https://maro5.com/members/kakaotalk_login/'

    RUNSERVER = 'runserver' in sys.argv
    if RUNSERVER:
        kakaotalk_redirect_uri = 'http://localhost:8000/members/kakaotalk_login/'

    params = {
        'grant_type':'authorization_code',
        'client_id':KAKAOTALK_REST_API_KEY,
        'redirect_uri':kakaotalk_redirect_uri,
        'code':code
    }

    response = requests.post(url,params)
    response_dict = response.json()
    access_token = response_dict['access_token']
    # return HttpResponse(access_token)


    # 3. access token 이용해서 app loigin
    # 엡연결-로긴 은 로그인한 사용자와 앱을 카카오 플랫폼에 연결함으로서
    # 일반적인 사용자가 앱 가입/등록 요청을 하는 경우와 비슷하다.
    # 카카오 서비스 이용하기 위해서 로그인 후 앱연결 선행되야 하고 앱연결 올바로 수행되면 사용자대한 고유한 아이디 부여된다.
    url = "https://kapi.kakao.com/v1/user/signup"
    headers = {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Cache-Control': 'no-cache',
    }
    headers.update({'Authorization':'Bearer ' + str(access_token)})
    response = requests.post(url, headers=headers)
    # return HttpResponse(response)


    # 4. acces _token 이용해서 사용자 정보 요청.
    # 사용자의 id, 카카오 계정 email 및 상세정보 얻어올 수 있는 기능.
    # 사용자 로그인 후 얻은 사용자토큰, 엡연결이 되어있어야 한다.
    url = "https://kapi.kakao.com/v1/user/me"
    response = requests.post(url, headers=headers)
    # return HttpResponse(response)

    response_dict = response.json()

    #5. 받아온 정보 중 회원가입에 필요한 요소들 꺼내기 및 회원 가입
    id = response_dict['id']
    email = response_dict['kaccount_email']
    nickname = response_dict['properties']['nickname']
    url_img_profile = response_dict['properties']['profile_image']#['url']

    # 있으면 get없으면 create하고 True도 같이 반환 .
    user, user_created = User.objects.get_or_create(
        username = id,
        email = email,
    )

    login(request, user,backend='django.contrib.auth.backends.ModelBackend')

    # return redirect('index')

    if user is not None:
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')

        # 어떤 함수 테스트 중인지도 전달해 주겠다.
        frame = inspect.currentframe()
        function_name = inspect.getframeinfo(frame).function
        context = {'function_name': function_name}

        return render(request,'social_login_succed.html',context)

    return redirect('login_page')



def naver_login(request):

    # 1. code 받기
    code = request.GET.get('code')
    state = request.GET.get('state')
    # return HttpResponse(state)


    # 2 .access token 받기
    url = "https://nid.naver.com/oauth2.0/token"
    naver_redirect_uri = 'https://maro5.com/members/kakaotalk_login/'

    RUNSERVER = 'runserver' in sys.argv
    if RUNSERVER:
        naver_redirect_uri = 'http://localhost:8000/members/kakaotalk_login/'

    params = {
        'grant_type':'authorization_code',
        'client_id':NAVER_CLIENT_ID,
        'client_secret':NAVER_CLIENT_SECRET,
        'redirect_uri':naver_redirect_uri,
        'code':code,
        'state':state
    }

    response = requests.post(url,params)
    response_dict = response.json()
    access_token = response_dict['access_token']
    # return HttpResponse(access_token)

    #
    # # 3. access token 이용해서 회원프로필 조회
    url = "https://openapi.naver.com/v1/nid/me"
    headers = {
        'Authorization': 'Bearer ' + str(access_token)
    }
    response = requests.post(url, headers=headers)
    # return HttpResponse(response)

    response_dict = response.json()

    #4. 받아온 정보 중 회원가입에 필요한 요소들 꺼내기 및 회원 가입
    id = response_dict['response']['id']
    email = response_dict['response']['email']

    # 있으면 get없으면 create하고 True도 같이 반환 .
    user, user_created = User.objects.get_or_create(
        username = id,
        email = email,
    )

    login(request, user,backend='django.contrib.auth.backends.ModelBackend')

    # return redirect('index')

    if user is not None:
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')

        # 어떤 함수 테스트 중인지도 전달해 주겠다.
        frame = inspect.currentframe()
        function_name = inspect.getframeinfo(frame).function
        context = {'function_name': function_name}

        return render(request,'social_login_succed.html',context)

    return redirect('login_page')


def google_login(request):

    # 1. access token 얻기

    code = request.GET.get('code')
    # return HttpResponse(code)

    url = 'https://www.googleapis.com/oauth2/v4/token'

    redirect_uri = 'https://maro5.com/members/google_login/'
    RUNSERVER = 'runserver' in sys.argv
    if RUNSERVER:
        redirect_uri = 'http://localhost:8000/members/google_login/'

    params = {
        'grant_type': 'authorization_code',
        'client_id':GOOGLE_CLIENT_ID,
        'redirect_uri':redirect_uri ,
        'client_secret':GOOGLE_CLIENT_SECRET,
        'code':code,
    }

    response = requests.post(url,params)
    response_dict = response.json()
    access_token = response_dict['access_token']
    # return HttpResponse(access_token)



    # # 3. access token 이용해서 회원프로필 조회
    url = "https://www.googleapis.com/oauth2/v1/userinfo"

    params ={
        'access_token': access_token,'alt': 'json'
    }

    response = requests.get(url,params=params)
    # return HttpResponse(response)

    # {"id": "108743605198166301707", "name": "Sanmaro Na", "given_name": "Sanmaro", "family_name": "Na",
    #  "link": "https://plus.google.com/108743605198166301707",
    #  "picture": "https://lh6.googleusercontent.com/-cYOpZZldajQ/AAAAAAAAAAI/AAAAAAAABtw/q8-Hofd6_QY/photo.jpg",
    #  "gender": "male", "locale": "ko"}

    response_dict = response.json()



    # 4. 받아온 정보 중 회원가입에 필요한 요소들 꺼내기 및 회원 가입
    id = response_dict['id']
    given_name = response_dict['given_name']
    family_name = response_dict['family_name']

    # 있으면 get없으면 create하고 True도 같이 반환 .
    user, user_created = User.objects.get_or_create(
        username=id,
        defaults={
            'first_name': given_name,
            'last_name': family_name,
        }
    )

    login(request, user, backend='django.contrib.auth.backends.ModelBackend')

    # return redirect('index')

    if user is not None:
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')

        # 어떤 함수 테스트 중인지도 전달해 주겠다.
        frame = inspect.currentframe()
        function_name = inspect.getframeinfo(frame).function
        context = {'function_name': function_name}

        return render(request, 'social_login_succed.html', context)

    return redirect('login_page')


def login_page(request):

    facebook_redirect_uri = 'https://maro5.com/members/facebook_login/'
    kakaotalk_redirect_uri = 'https://maro5.com/members/kakaotalk_login/'
    naver_redirect_uri = 'https://maro5.com/members/naver_login/'
    google_redirect_uri = 'https://maro5.com/members/google_login/'

    # 런서버 중이면 로컬 호스트로 redirect 시케겠다.
    RUNSERVER = 'runserver' in sys.argv
    if RUNSERVER:
        facebook_redirect_uri = 'http://localhost:8000/members/facebook_login/'

app/members/views/__init__.py
from .login import *
from .logout import *
from .signup import *
from .user_detail import *
from .signout import *

app/members/views/login.py
import inspect
import sys

import django
from django.contrib.auth import get_user_model, login, authenticate
from django.http import HttpResponse
from django.shortcuts import render, redirect

import requests

# Create your views here.
import members
from config.settings.base import *
User = get_user_model()


def normal_login(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)

    return redirect('main_page')

def facebook_login(request):

    code = request.GET.get('code')
    user = authenticate(request, code=code)

    if user is not None:
        login(request, user)

    return redirect('main_page')

def kakaotalk_login(request):

    code = request.GET.get('code')
    user = authenticate(request, code=code)

    if user is not None:
        login(request, user)

    return redirect('main_page')

def naver_login(request):

    # 1. code 받기
    code = request.GET.get('code')
    state = request.GET.get('state')
    user = authenticate(request, code=code,state=state)

    if user is not None:
        login(request, user)

    return redirect('main_page')

def google_login(request):

    code = request.GET.get('code')
    user = authenticate(request, code=code)

    if user is not None:
        login(request, user)

    return redirect('main_page')

def login_page(request):

    # 런서버 중이면 로컬 호스트로 redirect 시케겠다.
    RUNSERVER = 'runserver' in sys.argv
    if RUNSERVER:
        facebook_redirect_uri = 'http://localhost:8000/members/facebook_login/'
        kakaotalk_redirect_uri = 'http://localhost:8000/members/kakaotalk_login/'
        naver_redirect_uri = 'http://localhost:8000/members/naver_login/'
        google_redirect_uri = 'http://localhost:8000/members/google_login/'
    else:
        facebook_redirect_uri = 'https://maro5.com/members/facebook_login/'
        kakaotalk_redirect_uri = 'https://maro5.com/members/kakaotalk_login/'
        naver_redirect_uri = 'https://maro5.com/members/naver_login/'
        google_redirect_uri = 'https://maro5.com/members/google_login/'

    context = {"facebook_redirect_uri":facebook_redirect_uri,
               "fecebook_app_id":FACEBOOK_APP_ID,
               "kakaotalk_redirect_uri":kakaotalk_redirect_uri,
               "kakaotalk_rest_api_key": KAKAOTALK_REST_API_KEY,
               "naver_redirect_uri": naver_redirect_uri,
               "naver_client_id": NAVER_CLIENT_ID,
                "google_client_id": GOOGLE_CLIENT_ID,
               "google_redirect_uri":google_redirect_uri
               }



    return render(request, 'members/login.html',context =context)

app/members/views/logout.py
from django.contrib.auth import logout
from django.shortcuts import render


def logout_view(request):
    if request.method == 'POST':
        logout(request)
    return render(request,'members/login.html')

app/members/views/signout.py
from django.contrib.auth import logout
from django.shortcuts import render, redirect

from django.contrib.auth import get_user_model
User = get_user_model()


def signout_view(request):
    if request.method == 'POST':
        user = request.user
        logout(request)
        user.delete()
    return redirect('main_page')

app/movies/urls/views.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .. import views

app_name = 'movies'

urlpatterns = [
    path('main_page_by_date',views.main_page, name='main_page_by_date'),
    path('main_page_by_rating', views.main_rating_page, name='main_page_by_rating'),
    path('main_page_by_genre',views.main_genre_page, name='main_page_by_genre'),
    path('<int:pk>',views.movie_detail,name='movie_detail')
]+ static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

app/templates/members/account_activate_email.html
{{user.username}}님, 아래 링크를 클릭해서 계정을 활성화 해주세요.



{% if  domain == "maro5.com"%}
https://{{domain}}{% url 'members-api:activate' uidb64=uid token=token %}

{% else %}
http://{{domain}}{% url 'members:activate' uidb64=uid token=token %}

{% endif %}

app/templates/members/email_change.html
{% extends '../base.html'%}
{% block content %}



        <br>
        <br>

        <h2># 이메일 변경 #</h2>
        <div>
            <h5>새 이메일</h5>
            <form action="{% url 'members:user_email_change_page' %}" method="POST">
                {% csrf_token %}
                <input type="email" name = "email" value="{{email_decoded}}">
                <button type="submit" class="btn btn-primary">인증 메일 전송 </button>
            </form>
        </div>


        <div>
            <h5>인증번호</h5>
            <form action="{% url 'members:user_email_change' uidb64=uid token=token email=email %}" method="POST">
                {% csrf_token %}
                <input type="send_number" name = "send_number">
                <button type="submit" class="btn btn-primary">인증번호 인증 </button>
            </form>
        </div>



{% endblock %}

app/templates/members/email_sent_succeed.html
{% extends '../base.html'%}
{% block content %}

        <br>
        <br>

        <h1>##### 인증메일발송 완료  #####</h1>
        <div>
            입력하신 이메일 주소로 메일 인증메일 발송됬으니 확인후 다시 로그인 시도 부탁드립니다.
        </div>

{% endblock %}

app/templates/members/login.html
{% extends '../base.html'%}
{% load socialaccount %}
{% block content %}





        {% if user.is_authenticated %}
        {% else %}

        <br>
        <br>

        <h1># 일반 login #</h1>
        <div>
            <form action="{% url 'members:normal_login' %}" method="POST">
                {% csrf_token %}
                <input type="id" name = "username">
                <input type="password" name = "password">
                <button type="submit" class="btn btn-primary">normal login</button>
            </form>
        </div>


        <h1># 개별 view이용한 social lgoin #</h1>
        <h2>Facebook login </h2>
        <a href=" https://www.facebook.com/v3.0/dialog/oauth?
        client_id={{fecebook_app_id}}
        &redirect_uri={{facebook_redirect_uri}}
        &scope=email,public_profile" class="btn btn-primary">facebook login</a>




        <h2>Kakao login</h2>
        <a href="https://kauth.kakao.com/oauth/authorize?client_id={{kakaotalk_rest_api_key}}&redirect_uri={{kakaotalk_redirect_uri}}&response_type=code"
           class="btn btn-primary">kakaotalk login</a>


        <h2>Naver login</h2>
        <a href="https://nid.naver.com/oauth2.0/authorize?response_type=code&client_id={{naver_client_id}}&redirect_uri={{naver_redirect_uri}}&state=RAMDOM_STATE"
           class="btn btn-primary">Naver login</a>


        <h2>Google login </h2>
        <a href="https://accounts.google.com/o/oauth2/v2/auth?scope=https://www.googleapis.com/auth/userinfo.profile&redirect_uri={{google_redirect_uri}}&response_type=code&client_id={{google_client_id}}"
         class="btn btn-primary">Google login</a>



        <h1># allauth github login #</h1>
        <a href="{% provider_login_url 'github' %}" class="btn btn-primary">Github login</a>

        {% endif %}


{% endblock %}

app/templates/members/password_change.html
{% extends '../base.html'%}
{% block content %}



        <br>
        <br>

        <h2># 비밀번호 변경 #</h2>
        <div>
            <h5>새 비밀번호</h5>
            <form action="{% url 'members:user_password_change_page' %}" method="POST">
                {% csrf_token %}
                <input type="password" name = "password" value="{{password}}">
                <button type="submit" class="btn btn-primary">인증 메일 전송 </button>
            </form>
        </div>


        <div>
            <h5>인증번호</h5>
            <form action="{% url 'members:user_password_change' uidb64=uid token=token password=password %}" method="POST">
                {% csrf_token %}
                <input type="send_number" name = "send_number">
                <button type="submit" class="btn btn-primary">인증번호 인증 </button>
            </form>
        </div>



{% endblock %}

app/templates/members/phone_number_change.html
{% extends '../base.html'%}
{% block content %}



        <br>
        <br>

        <h2># 휴대폰번호 변경 #</h2>
        <div>
            <h5>새 휴대폰번호</h5>
            <form action="{% url 'members:user_phone_number_change_page' %}" method="POST">
                {% csrf_token %}
                <input type="phone_number" name = "phone_number" value="{{phone_number_decoded}}">
                <button type="submit" class="btn btn-primary">인증 문자 전송 </button>
            </form>
        </div>


        <div>
            <h5>인증번호</h5>
            <form action="{% url 'members:user_phone_number_change' uidb64=uid token=token phone_number=phone_number %}" method="POST">
                {% csrf_token %}
                <input type="send_number" name = "send_number">
                <button type="submit" class="btn btn-primary">인증번호 인증 </button>
            </form>
        </div>



{% endblock %}

app/templates/members/signup.html
{% extends '../base.html'%}
{% block content %}


        <br>
        <br>

        <h1># 회원가입 #</h1>
        <div>

            <form action="{% url 'members:signup_page' %}" enctype="multipart/form-data" method="POST">

                {{  form.non_field_errors }}
                {% csrf_token %}
                {% for field in form %}
                <div clsss="form-group">
                    <label for="{{field.id_for_label}}" style="color: #F0FFFF;">{{ field.label }}</label>
                    {{field}}
                    {{field.errors}}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary" style="float:right">회원가입</button>
            </form>
            
        </div>


{% endblock %}

app/templates/members/user_detail.html
{% extends '../base.html'%}
{% block content %}


        <br>
        <br>

        <h2># My page # </h2>

        <div>

            <a href="{% url 'members:user_info_change_page' %}" class="btn btn-primary">회원정보수정 </a>
            <a href="{% url 'members:user_movie_like_page' %}" class="btn btn-primary">찜 목록</a>
            <a href="{% url 'members:user_set_alarm_page' %}" class="btn btn-primary">알람설정</a>
            <div style="float; display:inline-block;" >
                <form action="{% url 'members:signout_view' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary" >회원탈퇴</button>
                </form>
            </div>

        </div>


{% endblock %}

app/templates/members/user_info_change.html
{% extends '../base.html'%}
{% block content %}


    <br>
    <br>

    <h2># 회원정보 수정 페이지 # </h2>

    <div>

        <p>username: {{user.username}}</p>

        {% if user.password %}
        <p>password</p>
                <form action="{% url 'members:user_password_change_page' %}" method="GET">
                    <button type="submit" class="btn btn-primary" > 비밀번호 변경 </button>
                </form>

        {% endif %}

        <p>email: {{user.email}}</p>
            <form action="{% url 'members:user_email_change_page' %}" method="GET">
                <button type="submit" class="btn btn-primary" > 이메일 변경 </button>
            </form>


        <p>phone_number: {{user.phone_number}}</p>
            <form action="{% url 'members:user_phone_number_change_page' %}" method="GET">
                <button type="submit" class="btn btn-primary" > 휴대폰번호 변경 </button>
            </form>




    </div>


{% endblock %}

app/templates/members/user_info_change_email.html
{{user.username}}님, 인증번호 시 회원정보 변경이 완료됩니다.
인증번호 : {{send_number}}

app/templates/members/user_info_change_fail_page.html
{% extends '../base.html'%}
{% block content %}


    <br>
    <br>

    <h3># 만료된 링크입니다. 다시 시도해 주세요! # </h3>


{% endblock %}

app/templates/members/user_info_change_succeed_page.html
{% extends '../base.html'%}
{% block content %}


    <br>
    <br>

    <h3># 회원정보 수정이 완료되었습니다. # </h3>


{% endblock %}

app/templates/members/user_movie_like_page.html
{% extends '../base.html'%}
{% block content %}


        <br>
        <br>

        <h2># 찜 목록 # </h2>

        <div class="container">
            <div class="row">
                {% for movie in like_movie_list %}
                <div class="col-4 mb-3">
                    <a href="{% url 'movies:movie_detail' pk=movie.pk %}"><div class="card-img-top" style="height: 177px; width: 309px; background-image: url('{{movie.thumbnail_url}}'); background-size: cover;">
                        {% if user.is_authenticated %}
                            <div style="float:right; display:inline-block;" >

                                <form action="{% url 'members:user_movie_like' pk=movie.pk %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ request.path }}">
                                    <!--뷰 호출한 곳으로 다시돌아가기(찜의 경우 다양한 템플릿에서 post요청 받기 때문에 )-->

                                    {% if movie in user.like_movies %}
                                    <button type="submit" class="btn btn-danger btn-xs" >찜취소</button>
                                    {% else %}
                                    <button type="submit" class="btn btn-success btn-xs" >찜하기</button>
                                    {% endif %}
                                </form>
                            </div>
                        {% endif %}
                    </div></a>
                    <div class="card-body">
                        <h5 class="card-title">{{movie.title}}</h5>
                        <p class="card-text">일시: {{movie.when}}</p>
                        <p class="card-text">장소: <a href="https://search.naver.com/search.naver?sm=top_hty&fbm=1&ie=utf8&query={{movie.library.library_name}}">{{movie.library.library_name}}</a> {{movie.place}}</p>
                    </div>

                </div>
                {% endfor %}


            </div>
        </div>




{% endblock %}

app/templates/members/user_set_alarm_page.html
{% extends '../base.html'%}
{% block content %}


        <br>
        <br>

        <h2># 알람설정 # </h2>

        <div style="float:left; display:inline-block; margin: 5px 5px;" >

            <form action="{% url 'members:user_set_alarm' type_num=24 %}" method="POST">
                {% csrf_token %}
                {% if user.set_alarm_before_24h %}
                    <button type="submit" class="btn btn-danger btn-xs" >24시간 이전 알람 취소 </button>
                {% else %}
                    <button type="submit" class="btn btn-success btn-xs" >24시간 이전 알람 설정</button>
                {% endif %}
            </form>

        </div>

        <div style="float:left; display:inline-block; margin: 5px 5px;" >

            <form action="{% url 'members:user_set_alarm' type_num=3 %}" method="POST">
                {% csrf_token %}
                {% if user.set_alarm_before_3h %}
                    <button type="submit" class="btn btn-danger btn-xs" >3시간 이전 알람 취소 </button>
                {% else %}
                    <button type="submit" class="btn btn-success btn-xs" >3시간 이전 알람 설정</button>
                {% endif %}
            </form>

        </div>



{% endblock %}