app/movies/models/movie.py
from django.db import models
from .locations import Library

__all__ =(
    'Movie',
    )


class Movie (models.Model):
    library = models.ForeignKey(Library, related_name='movies',on_delete=models.CASCADE)

    title = models.CharField(max_length=200)
    when = models.DateTimeField(auto_now=False, auto_now_add=False,blank=True)
    place = models.CharField(max_length=200,blank=True)
    runtime = models.CharField(max_length=100,blank=True)

    # 이하는 네이버 영화 검색으로 넣을것.
    director = models.CharField(max_length=200)
    thumbnail_url = models.CharField(max_length=200)
    story = models.TextField(blank=True)
    age = models.CharField(max_length=200, blank=True)
    rating = models.FloatField(default=0, blank=True)
    genre = models.CharField(max_length=200, blank=True)

    # 생성일 추가
    created_at = models.DateTimeField(auto_now_add=True)

app/members/urls/views.py
from django.urls import path, include
from ..import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'members'

urlpatterns = [

    path('login_page/', views.login_page, name='login_page'),
    path('normal_login/', views.normal_login, name='normal_login'),
    path('logout_view/',views.logout_view, name='logout_view'),
    path('signup_page/', views.signup,name='signup_page'),
    path('activate/<str:uidb64>/<str:token>', views.user_activate, name='activate'),
    path('signout_view/',views.signout_view, name='signout_view'),

    path('facebook_login/', views.facebook_login, name='facebook_login'),
    path('kakaotalk_login/', views.kakaotalk_login, name='kakaotalk_login'),
    path('naver_login/', views.naver_login, name='naver_login'),
    path('google_login/', views.google_login, name='google_login'),

    path('user_detail_page/', views.user_detail_page, name='user_detail_page'),

    path('user_info_change/', views.user_info_change_page, name='user_info_change_page'),
    path('user_password_change_page/', views.user_password_change_page, name='user_password_change_page'),
    path('user_password_change/<str:uidb64>/<str:token>/<str:password>', views.user_password_change, name='user_password_change'),
    path('user_email_change_page/', views.user_email_change_page, name='user_email_change_page'),
    path('user_email_change/<str:uidb64>/<str:token>/<str:email>', views.user_email_change,name='user_email_change'),
    path('user_phone_number_change_page/', views.user_phone_number_change_page, name='user_phone_number_change_page'),
    path('user_phone_number_change/<str:uidb64>/<str:token>/<str:phone_number>', views.user_phone_number_change, name='user_phone_number_change'),

    path('user_detail_page/user_movie_like_page/', views.user_movie_like_page, name='user_movie_like_page'),
    path('user_detail_page/<int:pk>/user_movie_like/', views.user_movie_like, name = 'user_movie_like'),

    path('user_detail_page/user_set_alarm_page/', views.user_set_alarm_page, name = 'user_set_alarm_page'),
    path('user_detail_page/<int:type_num>/user_set_alarm/', views.user_set_alarm, name = 'user_set_alarm'),

]+ static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

app/movies/apis/main.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from movies.models import Movie
from movies.serializers import MovieMainSerializer, MovieMainGenreSerializer, MovieMainDistamceSerializer


class MovieListByDate(APIView):

    def get(self, request, format=None):
        movies = Movie.objects.order_by('when')

        # 날짜 지난 친구들은 안보여주겠다면 주석 풀어라
        # movies_filtered = list()
        # now = timezone.now()
        # for movie in movies:
        #     if movie.when >= now:
        #         movies_filtered.append(movie)

        serializer = MovieMainSerializer(movies, many=True)

        return Response(serializer.data, status=status.HTTP_200_OK)


class MovieListByGenre(APIView):

    def get(self, request, format=None):
        movies = Movie.objects.order_by('genre','when')

        # 날짜 지난 친구들은 안보여주겠다면 주석 풀어라
        # movies_filtered = list()
        # now = timezone.now()
        # for movie in movies:
        #     if movie.when >= now:
        #         movies_filtered.append(movie)

        serializer = MovieMainGenreSerializer(movies, many=True)

        return Response(serializer.data, status=status.HTTP_200_OK)


class MovieListByRating(APIView):

    def get(self, request, format=None):
        movies = Movie.objects.order_by('-rating')

        # 날짜 지난 친구들은 안보여주겠다면 주석 풀어라
        # movies_filtered = list()
        # now = timezone.now()
        # for movie in movies:
        #     if movie.when >= now:
        #         movies_filtered.append(movie)

        serializer = MovieMainGenreSerializer(movies, many=True)

        return Response(serializer.data, status=status.HTTP_200_OK)


class MovieListByDistance(APIView):

    def get(self, request, format=None):
        movies = Movie.objects.order_by('when')

        serializer = MovieMainDistamceSerializer(movies, many=True)

        return Response(serializer.data, status=status.HTTP_200_OK)

app/movies/urls/views.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .. import views

app_name = 'movies'

urlpatterns = [
    path('main_page_by_date',views.main_page, name='main_page_by_date'),
    path('main_page_by_rating', views.main_rating_page, name='main_page_by_rating'),
    path('main_page_by_genre',views.main_genre_page, name='main_page_by_genre'),
    path('<int:pk>',views.movie_detail,name='movie_detail')
]+ static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

app/templates/movie/alarm_form.html
영화 상영정보

    영화제목 : {{title}}

    일시 : {{when}}

    장소 : {{library}}, {{place}}


상영취소되는 경우도 있으니 아래링크의 도서관 전화번호 혹은 홈페이지에서 확인하시기 바랍니다.

https://search.naver.com/search.naver?sm=top_hty&fbm=1&ie=utf8&query={{search_query}}

app/templates/movie/daily_crawling_result_mail_form.html
1. 업데이트된 영화

{% for key, value in dict_log.updated_movie.items %}
    지역 : {{key}}

    영화 수 : {{value.num}}

    목록 :

        {% for movie in value.list %}
            {{movie}}
        {% endfor %}

{% endfor %}


2. 네이버 검색 실패한 영화

{% for key, value in dict_log.no_extra_info_movie.items %}
    지역 : {{key}}

    영화 수 : {{value.num}}

    목록 :

        {% for movie in value.list %}
            {{movie}}
        {% endfor %}

{% endfor %}


3. 기간(현제월 앞뒤한달) 벋어나서 삭제한 영화

{% for key, value in dict_log.deleted_movie.items %}
    지역 : {{key}}

    영화 수 : {{value.num}}

    목록 :

        {% for movie in value.list %}
            {{movie}}
        {% endfor %}

{% endfor %}

4.전체 영화 총계

{% for key, value in dict_log.total_movie.items %}
    지역 : {{key}}

    이전 월 : {{value.before}}
    현제 월 : {{value.now}}
    다음 월 : {{value.after}}

{% endfor %}

app/templates/movie/main.html
{% extends '../base.html'%}




{% block content %}




    <div id="gnb" style="float:right; display:inline-block;">
        <ul>

            <li class="menu3">
                <a href="">정렬 </a>
                <dl class="dropdown">
                    <dd><a href="{% url 'movies:main_page_by_date' %}"> 날짜순 정렬</a></dd>
                    <dd><a href="{% url 'movies:main_page_by_genre' %}"> 장르별 정렬 </a></dd>
                    <dd><a href="{% url 'movies:main_page_by_rating' %}"> 평점순 정렬 </a></dd>
                </dl>
            </li>
        </ul>
    </div>

    <br><br><br><br><br><br>

<div class="container">
    <div class="row">
        {% for movie in movies %}
        <div class="col-4 mb-3">
            <a href="{% url 'movies:movie_detail' pk=movie.pk %}"><div class="card-img-top" style="height: 177px; width: 309px; background-image: url('{{movie.thumbnail_url}}'); background-size: cover;">
                    {% if user.is_authenticated %}
                        <div style="float:right; display:inline-block;" >

                            <form action="{% url 'members:user_movie_like' pk=movie.pk %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="next" value="{{ request.path }}">
                                {% if movie in user.like_movies %}
                                <button type="submit" class="btn btn-danger btn-xs" >찜취소</button>
                                {% else %}
                                <button type="submit" class="btn btn-success btn-xs" >찜하기</button>
                                {% endif %}
                            </form>
                        </div>
                    {% endif %}
            </div></a>
            <div class="card-body">
                <h5 class="card-title">{{movie.title}}</h5>
                <p class="card-text">{{movie.when}}</p>
            </div>
            
        </div>
        {% endfor %}
         
        
    </div>
</div>

{% endblock %}

app/templates/movie/main_genre.html
{% extends '../base.html'%}


{% block content %}
    <div id="gnb" style="float:right; display:inline-block;">
        <ul>

            <li class="menu3">
                <a href="">정렬 </a>
                <dl class="dropdown">
                    <dd><a href="{% url 'movies:main_page_by_date' %}"> 날짜순 정렬</a></dd>
                    <dd><a href="{% url 'movies:main_page_by_genre' %}"> 장르별 정렬 </a></dd>
                    <dd><a href="{% url 'movies:main_page_by_rating' %}"> 평점순 정렬 </a></dd>
                </dl>
            </li>
        </ul>
    </div>

    <br><br><br><br><br><br>


<div class="container">



    {% for genre in genre_list %}

    {% if genre == "" %}
        <h2> 기타 </h2>
    {% else %}
        <h2> {{genre}} </h2>
    {% endif %}

    <div class="row">
        {% for movie in movies %}
            {% if genre == movie.genre %}
                <div class="col-4 mb-3">
                <a href="{% url 'movies:movie_detail' pk=movie.pk %}"><div class="card-img-top" style="height: 177px; width: 309px; background-image: url('{{movie.thumbnail_url}}'); background-size: cover;">

                        {% if user.is_authenticated %}
                        <div style="float:right; display:inline-block;" >

                            <form action="{% url 'members:user_movie_like' pk=movie.pk %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="next" value="{{ request.path }}">
                                {% if movie in user.like_movies %}
                                <button type="submit" class="btn btn-danger btn-xs" >찜취소</button>
                                    {% else %}
                                <button type="submit" class="btn btn-success btn-xs" >찜하기</button>
                                {% endif %}
                            </form>
                        </div>
                        {% endif %}

                </div></a>
                    <div class="card-body">
                        <h5 class="card-title">{{movie.title}}</h5>
                        <p class="card-text">{{movie.when}}</p>
                    </div>

                </div>
            {% endif %}
        {% endfor %}
    </div>

    {% endfor %}

</div>

{% endblock %}

app/templates/movie/movie_detail.html
{% extends '../base.html'%}


{% block content %}

<br>
<br>
<div class="card bg-dark text-white">

        <div class="card-img-top" style="height: 354px; width: 618px; background-image: url('{{movie.thumbnail_url}}'); margin: 20px;  background-size: cover;">

            {% if user.is_authenticated %}
                <div style="float:right; display:inline-block;" >

                    <form action="{% url 'members:user_movie_like' pk=movie.pk %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}">
                        {% if movie in user.like_movies %}
                            <button type="submit" class="btn btn-danger btn-xs" >찜취소</button>
                        {% else %}
                            <button type="submit" class="btn btn-success btn-xs" >찜하기</button>
                        {% endif %}
                    </form>
                </div>
            {% endif %}

        </div>
            <div class="card-body">
                <h4 class="card-title">{{movie.title}}</h4>

                {% if movie.genre %}
                    <p class="card-text">장르 : {{movie.genre}}</p>
                {% endif %}

                {% if movie.director %}
                    <p class="card-text">감독 : {{movie.director}}</p>
                {% endif %}

                {% if movie.rating %}
                    <p class="card-text">평점 : {{movie.rating}}</p>
                {% endif %}

                {% if movie.age %}
                    <p class="card-text">시청연령 : {{movie.age}}</p>
                {% endif %}

                {% if movie.runtime %}
                    <p class="card-text">런타임 : {{movie.runtime}} 분 </p>
                {% endif %}

                {% if movie.when %}
                    <p class="card-text">상영일: {{movie.when}}</p>
                {% endif %}

                {% if movie.library %}
                    <p class="card-text">장소: <a href="https://search.naver.com/search.naver?sm=top_hty&fbm=1&ie=utf8&query={{movie.library.library_name}}">{{movie.library.library_name}}</a> {{movie.place}}</p>
                {% endif %}

                {% if movie.story %}
                    <p>줄거리: </p>
                    <span> {{movie.story}}</span>
                {% endif %}

            </div>



</div>

{% endblock %}