app/members/urls/views.py
from django.urls import path, include
from ..import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'members'

urlpatterns = [

    path('login_page/', views.login_page, name='login_page'),
    path('normal_login/', views.normal_login, name='normal_login'),
    path('logout_view/',views.logout_view, name='logout_view'),
    path('signup_page/', views.signup,name='signup_page'),
    path('activate/<str:uidb64>/<str:token>', views.user_activate, name='activate'),
    path('signout_view/',views.signout_view, name='signout_view'),

    path('facebook_login/', views.facebook_login, name='facebook_login'),
    path('kakaotalk_login/', views.kakaotalk_login, name='kakaotalk_login'),
    path('naver_login/', views.naver_login, name='naver_login'),
    path('google_login/', views.google_login, name='google_login'),

    path('user_detail_page/', views.user_detail_page, name='user_detail_page'),

    path('user_info_change/', views.user_info_change_page, name='user_info_change_page'),
    path('user_password_change_page/', views.user_password_change_page, name='user_password_change_page'),
    path('user_password_change/<str:uidb64>/<str:token>/<str:password>', views.user_password_change, name='user_password_change'),
    path('user_email_change_page/', views.user_email_change_page, name='user_email_change_page'),
    path('user_email_change/<str:uidb64>/<str:token>/<str:email>', views.user_email_change,name='user_email_change'),
    path('user_phone_number_change_page/', views.user_phone_number_change_page, name='user_phone_number_change_page'),
    path('user_phone_number_change/<str:uidb64>/<str:token>/<str:phone_number>', views.user_phone_number_change, name='user_phone_number_change'),

    path('user_detail_page/user_movie_like_page/', views.user_movie_like_page, name='user_movie_like_page'),
    path('user_detail_page/<int:pk>/user_movie_like/', views.user_movie_like, name = 'user_movie_like'),

    path('user_detail_page/user_set_alarm_page/', views.user_set_alarm_page, name = 'user_set_alarm_page'),
    path('user_detail_page/<int:type_num>/user_set_alarm/', views.user_set_alarm, name = 'user_set_alarm'),

]+ static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <style type="text/css">
        body{
            background-color: #000000;
        }
        h5, h4, h3, h2, h1, span {
            color: #F0FFFF;
        }
        a {
            color: #F0FFFF;
        }
        p {
            color: #6495ED
        }



      #gnb{ background:#000000; width:150px; height:40px; line-height:40px; margin:0 auto; }
      #gnb ul li{ float:left; width:100px; color:#fff; text-align:center; }
      #gnb ul li a{ color:#fff; font-weight:bold; display:block; }
      #gnb ul li a:hover{ background:#666; }
      #gnb ul li dl.dropdown{ border:3px #ccc solid; background:#FFC; display:none; }
      #gnb ul li dl.dropdown dd{height:30px; line-height:30px; border-bottom:1px #ccc solid; }
      #gnb ul li dl.dropdown a{ color:#333;  padding:0 5px; }
      #gnb ul li dl.dropdown a:hover{ background:#F60; color:#fff; }

      #gnb ul li.menu3:hover .dropdown{ display:block; }



    </style>




</head>
<body>

<div class="container">

    <br>
    <h2><a href="{% url 'main_page' %}">동대문구 도서관 무료영화  관람정보 </a></h2>
    <br>

        {% if user.is_authenticated %}
    <br>
        <div><p>{{user}}로 로그인 중</p></div>
    <br>
        <div style="float:left; display:inline-block;" >
            <form action="{% url 'members:logout_view' %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary" >logout</button>
            </form>
        </div>

        <div style="float:left; display:inline-block;">
            <a href="{% url 'members:user_detail_page' %}" class="btn btn-primary">mypage</a>

        </div>
    <br>
        {% else %}
        <a href="{% url 'members:login_page' %}" class="btn btn-primary">로그인</a>
        <a href="{% url 'members:signup_page' %}" class="btn btn-primary">회원가입</a>
    <br>
        {% endif %}





    <div>
        {% block content %}

        {% endblock %}

    </div>
</div>

</body>
</html>

app/templates/facebook_login_succed.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
            <h3>facebook login succeed page</h3>
</body>
</html>